name: Build Realtek r8168 driver for OpenWrt

on:
  push:
    tags:
      - 8.**
  # schedule:
  #   - cron: "0 0 * * MON"


env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  KMOD_VERSION: 8.053.00
  RELEASE_URL: https://github.com/SunHHB/package_kernel_r8168/raw/master/.github/workflows/OpenWrt-NIC-Drivers-release.txt

jobs:
  build_r8168_Modules:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        sdk_url:
          - https://downloads.immortalwrt.org/releases/21.02.7/targets/x86/64/immortalwrt-sdk-21.02.7-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          - https://downloads.immortalwrt.org/releases/23.05.2/targets/x86/64/immortalwrt-sdk-23.05.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz

   steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt -yqq install $(sed -n "1{s/\r$//g;p;q}" $GITHUB_WORKSPACE/Depends.txt)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download SDK
      run: |
        url=${{ matrix.sdk_url }}
        sdk=$(basename $url | awk -F '.tar.xz' '{ print $1 }')

        wget $url
        tar xvf $sdk.tar.xz

        mkdir -p $sdk/package/r8168
        cp -r patches $sdk/package/r8168
        cp -r src $sdk/package/r8168
        cp -r Makefile $sdk/package/r8168

    - name: Compile
      run: |
        url=${{ matrix.sdk_url }}
        sdk=$(basename $url | awk -F '.tar.xz' '{ print $1 }')

        cd $sdk
        echo 'CONFIG_PACKAGE_kmod-r8168=m' > .config
        make defconfig
        
        make package/r8168/compile -j$(nproc) || make package/r8168/compile -j1 V=sc || exit 0

        # cp file to artifact
        cd ${{ github.workspace }}
        mkdir -p ${{ github.workspace }}/artifact

        for ipk in `find . -name 'kmod-r8168*.ipk'`; do
          cp $ipk ${{ github.workspace }}/artifact
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.KMOD_VERSION }}
        path: ${{ github.workspace }}/artifact/**/*

  deploy:
    needs: [build_r8168_Modules]
    name: Create release and upload artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.KMOD_VERSION }}

    - name: Upload build artifacts to cloud
      run: |
        mkdir -p ${{ github.workspace }}/artifact
        for ipk in `find . -name '*.ipk'`; do
          mv $ipk ${{ github.workspace }}/artifact
        done
        cd artifact && md5sum *.ipk > md5sum.txt
        cd ..


    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
      with:
        name: ${{ env.KMOD_VERSION }}
        tag_name: ${{ env.KMOD_VERSION }}
        files: artifact/**/*

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 2  
        delete_tags: true

    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v4
      with:
        name: ${{ env.KMOD_VERSION }}
